---
title: "Piracy and PIPA/SOPA"
subtitle: "This is our final project for Decision Making Under Uncertainty"
date: "April 25, 2026" 
author: 
    - Christian Auman
    - Nate Miller
    - Nathan 
    - Simran Gautam
output: 
    pdf_document:
        toc: true
        toc_depth: 2
        fig_width: 7
        fig_height: 6
        fig_caption: true
        df_print: kable
        highlight: tango
        latex_engine: xelatex
        keep_tex: true

fontsize: 11pt
linestretch: 1.5 
papersize: letter
geometry: margin=1in

header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{float}
  - \usepackage{caption}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyhead[L]{Piracy and PIPA/SOPA}
  - \fancyhead[R]{Decision Making Under Uncertainty}
  - \fancyfoot[C]{\thepage}
  - \setlength{\headheight}{14pt}
  - \usepackage{etoolbox}

  - \makeatletter
  - |
    \renewcommand{\maketitle}{
      \begin{titlepage}
      \thispagestyle{empty}
      \vspace*{\fill}

      \begin{center}
        {\LARGE \@title \par}
        \vspace{1em}

        {\large
        \lineskip .5em
        \begin{tabular}[t]{c}
        \@author
        \end{tabular}\par}

        \vspace{1em}
        {\large \@date \par}

        \vspace{2em}
        \begin{minipage}{0.7\textwidth}
        \centering
        \textbf{Abstract}\\[0.5em]
        We need to put something here which gives an abstract description of what we did and why it matters
        \end{minipage}
      \end{center}

      \vspace*{\fill}
      \end{titlepage}
    }
  - \makeatother

  - \pretocmd{\tableofcontents}{\thispagestyle{empty}}{}{}
  - \apptocmd{\tableofcontents}{\newpage}{}{}
lang: "en-US"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)

library(openintro)
```

# Introduction

Give a brief introductory paragraph on the project. 

## Project Motivation 

**Questions to Answer:**

- Why do we care?
- What are we doing?
- Briefly, how are we solving it?
- What is the data?
- Where does it come from?

## Data Source and Variables

> More in-depth overview about the data

- Population vs Sample
- Size:
  - How many observations? 
  - How many variables?
- Variables - describe each variable in the dataset (more than just it's type)

# Research Questions and Hypothesis

Give a brief introductory paragraph on this section.

## Research Question

- Define our primary question that our analysis will answer
- Describe how we came up with this question

## Our Hypothesis

- State null & alternative hypotheses in english
- Then describe them in statistics language (i.e. symbols)
- List 2-3 supporting questions we will investigate

# Main Analyses

Briefly describe this section.

## Exploratory Data Analysis

Give an overview of the plots we use & statistics we used and relate how they answer our research questions.

Describe the plot and how it helps answer a research question

**PLOT 1**
- PLOT 1 figcaption

Describe the plot and how it helps answer a research question

**PLOT 2**
- PLOT 2 figcaption

Describe the plot and how it helps answer a research question

**PLOT 3**
- PLOT 3 figcaption

## Statistical Methods

List the statistical analysis methods we used to answer our research question.

- Go through each method in separate sections
  - describe how each method answers one of our research question
  - explain the results of the particular analysis
  - define the analysis in proper statistics notation (i.e. with symbols)

# Discussion (Interpretation, uncertainty, assumptions)

*can merge this section into conclusion if we need to shorten the report*

Briefly interpret the results beyond the raw statistics.

- What do the results imply?
- Were the hypotheses supported?
- How should we understand the uncertainty?
- What assumptions did the analysis rely on?

# Conclusion (final answer, limitations, future work, why it matters)

Briefly summarize the project and directly answer the main research question.

## Summary of Findings

- Restate our finding: What did the tests conclude (in plain english)
- Answer our research question directly
- Supporting findings: What did the exploratory analyses reveal

## Limitations and Future Work

- Limitations: What are the weaknesses of our analysis? (most probably the correlation coefficient is not strong)
- Unanswered Questions: What remains unknown?
- Future research section
- Real-world meaning: So what? Why should anyone care about our findings?

